"""Update UserTransaction table

Revision ID: 7db34aa89454
Revises: d7ae82c49345
Create Date: 2024-04-16 18:38:11.805600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7db34aa89454'
down_revision = 'd7ae82c49345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.alter_column('accepted',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('usd_to_lbp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usd_to_lbp', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.alter_column('accepted',
               existing_type=sa.String(length=20),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)

    # ### end Alembic commands ###
