"""Remove credit_card column from User model

Revision ID: 7fa79ad5f3ef
Revises: 87bef8b91c3e
Create Date: 2024-04-15 22:58:31.264225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fa79ad5f3ef'
down_revision = '87bef8b91c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('credit_card')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_card', mysql.VARCHAR(length=16), nullable=True))

    # ### end Alembic commands ###
