"""Add credit_card column to User model

Revision ID: aadeb09f9cd6
Revises: a0d98cfbae03
Create Date: 2024-04-15 21:53:18.688466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aadeb09f9cd6'
down_revision = 'a0d98cfbae03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_card', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('credit_card')

    # ### end Alembic commands ###
