"""Rename reset_password_token to reset_password_OTP

Revision ID: b7710e8642dc
Revises: 71e81087acc0
Create Date: 2024-04-26 01:12:51.530476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7710e8642dc'
down_revision = '71e81087acc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_password_OTP', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('reset_OTP_expiration', sa.DateTime(), nullable=True))
        batch_op.drop_index('reset_password_token')
        batch_op.create_unique_constraint(None, ['reset_password_OTP'])
        batch_op.drop_column('reset_password_token')
        batch_op.drop_column('reset_token_expiration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token_expiration', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('reset_password_token', mysql.VARCHAR(length=32), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('reset_password_token', ['reset_password_token'], unique=True)
        batch_op.drop_column('reset_OTP_expiration')
        batch_op.drop_column('reset_password_OTP')

    # ### end Alembic commands ###
