"""Add created_at column to UserTransaction model

Revision ID: d81c9b9e357d
Revises: b7710e8642dc
Create Date: 2024-04-27 00:12:50.783799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81c9b9e357d'
down_revision = 'b7710e8642dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
