"""Add USD and LBP balances to User model

Revision ID: e429fdfcea31
Revises: 
Create Date: 2024-04-14 23:50:08.385806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e429fdfcea31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usd_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lbp_balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lbp_balance')
        batch_op.drop_column('usd_balance')

    # ### end Alembic commands ###
